### ISSUE TITLE
Overdub & Discussions: empty comment submit

### ISSUE THREAD

**Issue by kcorea-cltit** [llcit/clt-langlabs-dev-py#9]
- user can submit empty comment on page load, but not after a comment has been submitted
- this happens in the essay discussion thread as well, but an error occurs in the view before it is posted

`[09/Mar/2015 14:02:48] "POST /post/save/ HTTP/1.1" 500 11422
 ERROR Internal Server Error: /post/save/
 Traceback (most recent call last):
 File "/home/kenny/.virtualenvs/langlabs/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)
 File "/home/kenny/Projects/langlabs/clt-langlabs-dev-py/core/views.py", line 192, in savePost
   mess.save()
 UnboundLocalError: local variable 'mess' referenced before assignment
`

**Comment by richmedina** [comment]
Richard will address.
